# -*- coding: utf-8 -*-
#
# Copyright 2020 Xpp521
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Form implementation generated from reading ui file 'SettingWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
from Resources import resource
from PyQt5.QtCore import Qt, QRect
from Utils.SuggestionGetter import KeywordGetter
from Utils.Widgets import IconDelegate, SingleLevelMenu
from PyQt5.QtGui import QFont, QCursor, QFontDatabase, QStandardItemModel
from PyQt5.QtWidgets import QFrame, QLabel, QWidget, QLineEdit, QCheckBox, QGroupBox, QComboBox, QTableView,\
    QRadioButton, QPushButton, QTreeWidget, QTreeWidgetItem, QAbstractScrollArea, QAbstractItemView


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        QFontDatabase().addApplicationFont(resource.ttf.get('mvboli.ttf'))
        Dialog.setObjectName("MainWindow")
        Dialog.resize(1025, 675)
        Dialog.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinimizeButtonHint)
        Dialog.setAttribute(Qt.WA_TranslucentBackground)
        self.widget_left = QWidget(Dialog)
        self.widget_left.setGeometry(QRect(0, 0, 260, 675))
        font = QFont()
        font.setPointSize(9)
        self.widget_left.setFont(font)
        self.widget_left.setObjectName("widget_left")
        self.treeWidget = QTreeWidget(self.widget_left)
        self.treeWidget.setGeometry(QRect(0, 140, 260, 450))
        font = QFont()
        font.setFamily("Arial")
        self.treeWidget.setFont(font)
        self.treeWidget.setFocusPolicy(Qt.NoFocus)
        self.treeWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.treeWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.treeWidget.setIndentation(24)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QTreeWidgetItem(self.treeWidget)
        item_0 = QTreeWidgetItem(self.treeWidget)
        item_1 = QTreeWidgetItem(item_0)
        item_1 = QTreeWidgetItem(item_0)
        item_0 = QTreeWidgetItem(self.treeWidget)
        item_0 = QTreeWidgetItem(self.treeWidget)
        item_0 = QTreeWidgetItem(self.treeWidget)
        item_0 = QTreeWidgetItem(self.treeWidget)
        self.label_logo = QLabel(self.widget_left)
        self.label_logo.setGeometry(QRect(30, 20, 200, 100))
        font = QFont()
        font.setFamily("MV Boli")
        font.setPointSize(30)
        self.label_logo.setFont(font)
        self.label_logo.setObjectName("label_logo")
        self.widget_right = QWidget(Dialog)
        self.widget_right.setGeometry(QRect(260, 0, 765, 675))
        self.widget_right.setObjectName("widget_right")
        self.frame_advanced = QFrame(self.widget_right)
        self.frame_advanced.setGeometry(QRect(0, 50, 765, 600))
        self.frame_advanced.setFrameShape(QFrame.StyledPanel)
        self.frame_advanced.setFrameShadow(QFrame.Raised)
        self.frame_advanced.setObjectName("frame_advanced")
        self.label_no_sleep = QLabel(self.frame_advanced)
        self.label_no_sleep.setGeometry(QRect(40, 20, 600, 25))
        self.label_no_sleep.setObjectName("label_no_sleep")
        self.checkBox_no_sleep = QCheckBox(self.frame_advanced)
        self.checkBox_no_sleep.setGeometry(QRect(60, 60, 100, 20))
        self.checkBox_no_sleep.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_no_sleep.setObjectName("checkBox_no_sleep")
        self.label_backup = QLabel(self.frame_advanced)
        self.label_backup.setGeometry(QRect(40, 132, 600, 25))
        self.label_backup.setObjectName("label_backup")
        self.pushButton_import_settings = QPushButton(self.frame_advanced)
        self.pushButton_import_settings.setGeometry(QRect(190, 170, 100, 25))
        self.pushButton_import_settings.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_import_settings.setObjectName("pushButton_import_settings")
        self.pushButton_export_settings = QPushButton(self.frame_advanced)
        self.pushButton_export_settings.setGeometry(QRect(60, 170, 100, 25))
        self.pushButton_export_settings.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_export_settings.setObjectName("pushButton_export_settings")
        self.frame_search_other = QFrame(self.widget_right)
        self.frame_search_other.setGeometry(QRect(0, 50, 765, 600))
        self.frame_search_other.setFrameShape(QFrame.StyledPanel)
        self.frame_search_other.setFrameShadow(QFrame.Raised)
        self.frame_search_other.setObjectName("frame_search_other")
        self.checkBox_private_mode = QCheckBox(self.frame_search_other)
        self.checkBox_private_mode.setGeometry(QRect(60, 540, 91, 20))
        self.checkBox_private_mode.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_private_mode.setObjectName("checkBox_private_mode")
        self.label_private_mode = QLabel(self.frame_search_other)
        self.label_private_mode.setGeometry(QRect(40, 468, 600, 25))
        self.label_private_mode.setObjectName("label_private_mode")
        self.label_private_mode_tip1 = QLabel(self.frame_search_other)
        self.label_private_mode_tip1.setGeometry(QRect(60, 500, 690, 16))
        self.label_private_mode_tip1.setObjectName("label_private_mode_tip1")
        self.label_browser_path = QLabel(self.frame_search_other)
        self.label_browser_path.setGeometry(QRect(40, 356, 600, 25))
        self.label_browser_path.setObjectName("label_browser_path")
        self.pushButton_browser_path = QPushButton(self.frame_search_other)
        self.pushButton_browser_path.setGeometry(QRect(570, 400, 35, 25))
        self.pushButton_browser_path.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_browser_path.setFlat(False)
        self.pushButton_browser_path.setObjectName("pushButton_browser_path")
        self.lineEdit_browser_path = QLineEdit(self.frame_search_other)
        self.lineEdit_browser_path.setGeometry(QRect(60, 400, 500, 25))
        self.lineEdit_browser_path.setReadOnly(True)
        self.lineEdit_browser_path.setObjectName("lineEdit_browser_path")
        self.label_suggestion_engine = QLabel(self.frame_search_other)
        self.label_suggestion_engine.setGeometry(QRect(40, 132, 600, 25))
        self.label_suggestion_engine.setObjectName("label_suggestion_engine")
        self.comboBox_suggestion_engine = QComboBox(self.frame_search_other)
        self.comboBox_suggestion_engine.setGeometry(QRect(60, 170, 150, 22))
        self.comboBox_suggestion_engine.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_suggestion_engine.setObjectName("comboBox_suggestion_engine")
        self.comboBox_suggestion_engine.addItem('')
        self.comboBox_suggestion_engine.addItem('')
        self.comboBox_suggestion_engine.addItem('')
        self.comboBox_suggestion_engine.setItemData(0, KeywordGetter.QH360)
        self.comboBox_suggestion_engine.setItemData(1, KeywordGetter.DOGEDOGE)
        self.comboBox_suggestion_engine.setItemData(2, KeywordGetter.GOOGLE)
        self.label_search_suggestion = QLabel(self.frame_search_other)
        self.label_search_suggestion.setGeometry(QRect(40, 20, 600, 25))
        self.label_search_suggestion.setObjectName("label_search_suggestion")
        self.checkBox_search_suggestion = QCheckBox(self.frame_search_other)
        self.checkBox_search_suggestion.setGeometry(QRect(60, 60, 100, 20))
        self.checkBox_search_suggestion.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_search_suggestion.setObjectName("checkBox_search_suggestion")
        self.label_private_mode_tip2 = QLabel(self.frame_search_other)
        self.label_private_mode_tip2.setGeometry(QRect(60, 520, 690, 16))
        self.label_private_mode_tip2.setObjectName("label_private_mode_tip2")
        self.label_suggestion_clear_cache = QLabel(self.frame_search_other)
        self.label_suggestion_clear_cache.setGeometry(QRect(40, 244, 600, 25))
        self.label_suggestion_clear_cache.setObjectName("label_suggestion_clear_cache")
        self.pushButton_suggestion_clear_cache = QPushButton(self.frame_search_other)
        self.pushButton_suggestion_clear_cache.setGeometry(QRect(60, 310, 100, 25))
        self.pushButton_suggestion_clear_cache.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_suggestion_clear_cache.setObjectName("pushButton_suggestion_clear_cache")
        self.label_suggestion_cache_count1 = QLabel(self.frame_search_other)
        self.label_suggestion_cache_count1.setGeometry(QRect(60, 280, 150, 16))
        self.label_suggestion_cache_count1.setObjectName("label_suggestion_cache_count1")
        self.label_suggestion_cache_count2 = QLabel(self.frame_search_other)
        self.label_suggestion_cache_count2.setGeometry(QRect(210, 280, 100, 16))
        self.label_suggestion_cache_count2.setObjectName("label_suggestion_cache_count2")
        self.frame_hotkey = QFrame(self.widget_right)
        self.frame_hotkey.setGeometry(QRect(0, 50, 765, 600))
        self.frame_hotkey.setFrameShape(QFrame.StyledPanel)
        self.frame_hotkey.setFrameShadow(QFrame.Raised)
        self.frame_hotkey.setObjectName("frame_hotkey")
        self.label_key_type = QLabel(self.frame_hotkey)
        self.label_key_type.setGeometry(QRect(40, 20, 600, 25))
        self.label_key_type.setObjectName("label_key_type")
        self.radioButton_single_key = QRadioButton(self.frame_hotkey)
        self.radioButton_single_key.setGeometry(QRect(60, 60, 200, 20))
        self.radioButton_single_key.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton_single_key.setObjectName("radioButton_single_key")
        self.radioButton_multiple_key = QRadioButton(self.frame_hotkey)
        self.radioButton_multiple_key.setGeometry(QRect(60, 90, 200, 20))
        self.radioButton_multiple_key.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton_multiple_key.setObjectName("radioButton_multiple_key")
        self.lineEdit_key_setting = QLineEdit(self.frame_hotkey)
        self.lineEdit_key_setting.setGeometry(QRect(60, 200, 150, 22))
        self.lineEdit_key_setting.setReadOnly(True)
        self.lineEdit_key_setting.setObjectName("lineEdit_key_setting")
        self.label_key_setting_tip = QLabel(self.frame_hotkey)
        self.label_key_setting_tip.setGeometry(QRect(60, 170, 500, 16))
        self.label_key_setting_tip.setObjectName("label_key_setting_tip")
        self.label_key_setting = QLabel(self.frame_hotkey)
        self.label_key_setting.setGeometry(QRect(40, 132, 600, 25))
        self.label_key_setting.setObjectName("label_key_setting")
        self.comboBox_interval = QComboBox(self.frame_hotkey)
        self.comboBox_interval.setGeometry(QRect(60, 390, 150, 22))
        self.comboBox_interval.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_interval.setObjectName("comboBox_interval")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.label_interval = QLabel(self.frame_hotkey)
        self.label_interval.setGeometry(QRect(40, 356, 600, 25))
        self.label_interval.setObjectName("label_interval")
        self.comboBox_repetitions = QComboBox(self.frame_hotkey)
        self.comboBox_repetitions.setGeometry(QRect(60, 280, 150, 22))
        self.comboBox_repetitions.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_repetitions.setObjectName("comboBox_repetitions")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.label_repetitions = QLabel(self.frame_hotkey)
        self.label_repetitions.setGeometry(QRect(40, 244, 600, 25))
        self.label_repetitions.setObjectName("label_repetitions")
        self.frame_engine_management = QFrame(self.widget_right)
        self.frame_engine_management.setGeometry(QRect(0, 50, 765, 600))
        self.frame_engine_management.setFrameShape(QFrame.StyledPanel)
        self.frame_engine_management.setFrameShadow(QFrame.Raised)
        self.frame_engine_management.setObjectName("frame_engine_management")
        self.tableView_search_engine = QTableView(self.frame_engine_management)
        self.tableView_search_engine.setGeometry(QRect(40, 20, 685, 500))
        self.tableView_search_engine.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableView_search_engine.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableView_search_engine.setEditTriggers(
            QAbstractItemView.DoubleClicked | QAbstractItemView.SelectedClicked)
        self.tableView_search_engine.setTabKeyNavigation(False)
        self.tableView_search_engine.setProperty("showDropIndicator", False)
        self.tableView_search_engine.setCornerButtonEnabled(False)
        self.tableView_search_engine.setObjectName("tableView_search_engine")
        self.tableView_search_engine.horizontalHeader().setStretchLastSection(True)
        self.tableView_search_engine.verticalHeader().setVisible(False)
        self.tableView_search_engine.verticalHeader().setCascadingSectionResizes(True)
        self.tableView_search_engine.verticalHeader().setDefaultSectionSize(35)
        self.model = QStandardItemModel()
        self.model.setColumnCount(3)
        self.tableView_search_engine.setModel(self.model)
        self.table_menu = SingleLevelMenu(['set_default_engine', None, 'delete'], parent=self.tableView_search_engine)
        self.frame_basics = QFrame(self.widget_right)
        self.frame_basics.setGeometry(QRect(0, 50, 765, 600))
        self.frame_basics.setFrameShape(QFrame.StyledPanel)
        self.frame_basics.setFrameShadow(QFrame.Raised)
        self.frame_basics.setObjectName("frame_basics")
        self.label_start_up = QLabel(self.frame_basics)
        self.label_start_up.setGeometry(QRect(40, 20, 600, 25))
        self.label_start_up.setObjectName("label_start_up")
        self.label_show_tip = QLabel(self.frame_basics)
        self.label_show_tip.setGeometry(QRect(40, 132, 600, 25))
        self.label_show_tip.setObjectName("label_show_tip")
        self.checkBox_start_up = QCheckBox(self.frame_basics)
        self.checkBox_start_up.setGeometry(QRect(60, 60, 100, 20))
        self.checkBox_start_up.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_start_up.setObjectName("checkBox_start_up")
        self.checkBox_show_tip = QCheckBox(self.frame_basics)
        self.checkBox_show_tip.setGeometry(QRect(60, 170, 100, 20))
        self.checkBox_show_tip.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBox_show_tip.setObjectName("checkBox_show_tip")
        self.comboBox_language = QComboBox(self.frame_basics)
        self.comboBox_language.setGeometry(QRect(60, 280, 150, 22))
        self.comboBox_language.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_language.setObjectName("comboBox_language")
        from Languages import language_map
        for code, name in language_map.items():
            self.comboBox_language.addItem(name, code)
        self.label_language = QLabel(self.frame_basics)
        self.label_language.setGeometry(QRect(41, 244, 600, 25))
        self.label_language.setObjectName("label_language")
        self.frame_appearance = QFrame(self.widget_right)
        self.frame_appearance.setGeometry(QRect(0, 50, 765, 600))
        self.frame_appearance.setFrameShape(QFrame.StyledPanel)
        self.frame_appearance.setFrameShadow(QFrame.Raised)
        self.frame_appearance.setObjectName("frame_appearance")
        self.label_opacity = QLabel(self.frame_appearance)
        self.label_opacity.setGeometry(QRect(40, 20, 600, 25))
        self.label_opacity.setObjectName("label_opacity")
        self.comboBox_opacity = QComboBox(self.frame_appearance)
        self.comboBox_opacity.setGeometry(QRect(60, 60, 150, 22))
        self.comboBox_opacity.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_opacity.setObjectName("comboBox_opacity")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.label_fillet = QLabel(self.frame_appearance)
        self.label_fillet.setGeometry(QRect(40, 132, 600, 25))
        self.label_fillet.setObjectName("label_fillet")
        self.comboBox_fillet = QComboBox(self.frame_appearance)
        self.comboBox_fillet.setGeometry(QRect(60, 170, 150, 22))
        self.comboBox_fillet.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_fillet.setObjectName("comboBox_fillet")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.label_theme = QLabel(self.frame_appearance)
        self.label_theme.setGeometry(QRect(40, 356, 600, 25))
        self.label_theme.setObjectName("label_theme")
        self.label_distance = QLabel(self.frame_appearance)
        self.label_distance.setGeometry(QRect(40, 244, 600, 25))
        self.label_distance.setObjectName("label_distance")
        self.comboBox_distance = QComboBox(self.frame_appearance)
        self.comboBox_distance.setGeometry(QRect(60, 280, 150, 22))
        self.comboBox_distance.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_distance.setObjectName("comboBox_distance")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.groupBox_blue = QGroupBox(self.frame_appearance)
        self.groupBox_blue.setGeometry(QRect(40, 396, 70, 80))
        self.groupBox_blue.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_blue.setAlignment(Qt.AlignCenter)
        self.groupBox_blue.setFlat(False)
        self.groupBox_blue.setObjectName("groupBox_blue")
        self.pushButton_blue = QPushButton(self.groupBox_blue)
        self.pushButton_blue.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_blue.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_blue.setText("")
        self.pushButton_blue.setObjectName("pushButton_blue")
        self.groupBox_green = QGroupBox(self.frame_appearance)
        self.groupBox_green.setGeometry(QRect(130, 396, 70, 80))
        self.groupBox_green.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_green.setAlignment(Qt.AlignCenter)
        self.groupBox_green.setFlat(False)
        self.groupBox_green.setObjectName("groupBox_green")
        self.pushButton_green = QPushButton(self.groupBox_green)
        self.pushButton_green.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_green.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_green.setText("")
        self.pushButton_green.setObjectName("pushButton_green")
        self.groupBox_yellow = QGroupBox(self.frame_appearance)
        self.groupBox_yellow.setGeometry(QRect(220, 396, 70, 80))
        self.groupBox_yellow.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_yellow.setAlignment(Qt.AlignCenter)
        self.groupBox_yellow.setFlat(False)
        self.groupBox_yellow.setObjectName("groupBox_yellow")
        self.pushButton_yellow = QPushButton(self.groupBox_yellow)
        self.pushButton_yellow.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_yellow.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_yellow.setText("")
        self.pushButton_yellow.setObjectName("pushButton_yellow")
        self.groupBox_orange = QGroupBox(self.frame_appearance)
        self.groupBox_orange.setGeometry(QRect(310, 396, 70, 80))
        self.groupBox_orange.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_orange.setAlignment(Qt.AlignCenter)
        self.groupBox_orange.setFlat(False)
        self.groupBox_orange.setObjectName("groupBox_orange")
        self.pushButton_orange = QPushButton(self.groupBox_orange)
        self.pushButton_orange.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_orange.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_orange.setText("")
        self.pushButton_orange.setObjectName("pushButton_orange")
        self.groupBox_red = QGroupBox(self.frame_appearance)
        self.groupBox_red.setGeometry(QRect(400, 396, 70, 80))
        self.groupBox_red.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_red.setAlignment(Qt.AlignCenter)
        self.groupBox_red.setFlat(False)
        self.groupBox_red.setObjectName("groupBox_red")
        self.pushButton_red = QPushButton(self.groupBox_red)
        self.pushButton_red.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_red.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_red.setText("")
        self.pushButton_red.setObjectName("pushButton_red")
        self.groupBox_purple = QGroupBox(self.frame_appearance)
        self.groupBox_purple.setGeometry(QRect(490, 396, 70, 80))
        self.groupBox_purple.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_purple.setAlignment(Qt.AlignCenter)
        self.groupBox_purple.setFlat(False)
        self.groupBox_purple.setObjectName("groupBox_purple")
        self.pushButton_purple = QPushButton(self.groupBox_purple)
        self.pushButton_purple.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_purple.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_purple.setText("")
        self.pushButton_purple.setObjectName("pushButton_purple")
        self.groupBox_grey = QGroupBox(self.frame_appearance)
        self.groupBox_grey.setGeometry(QRect(580, 396, 70, 80))
        self.groupBox_grey.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_grey.setAlignment(Qt.AlignCenter)
        self.groupBox_grey.setFlat(False)
        self.groupBox_grey.setObjectName("groupBox_grey")
        self.pushButton_grey = QPushButton(self.groupBox_grey)
        self.pushButton_grey.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_grey.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_grey.setText("")
        self.pushButton_grey.setObjectName("pushButton_grey")
        self.groupBox_black = QGroupBox(self.frame_appearance)
        self.groupBox_black.setGeometry(QRect(670, 396, 70, 80))
        self.groupBox_black.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_black.setAlignment(Qt.AlignCenter)
        self.groupBox_black.setFlat(False)
        self.groupBox_black.setObjectName("groupBox_black")
        self.pushButton_black = QPushButton(self.groupBox_black)
        self.pushButton_black.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_black.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_black.setText("")
        self.pushButton_black.setObjectName("pushButton_black")
        self.groupBox_custom = QGroupBox(self.frame_appearance)
        self.groupBox_custom.setGeometry(QRect(40, 486, 70, 80))
        self.groupBox_custom.setCursor(QCursor(Qt.ArrowCursor))
        self.groupBox_custom.setAlignment(Qt.AlignCenter)
        self.groupBox_custom.setFlat(False)
        self.groupBox_custom.setCheckable(False)
        self.groupBox_custom.setObjectName("groupBox_custom")
        self.pushButton_custom = QPushButton(self.groupBox_custom)
        self.pushButton_custom.setGeometry(QRect(10, 20, 50, 50))
        self.pushButton_custom.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_custom.setText("")
        self.pushButton_custom.setObjectName("pushButton_custom")
        self.frame_about = QFrame(self.widget_right)
        self.frame_about.setGeometry(QRect(0, 50, 765, 600))
        self.frame_about.setFrameShape(QFrame.StyledPanel)
        self.frame_about.setFrameShadow(QFrame.Raised)
        self.frame_about.setObjectName("frame_about")
        self.label_update = QLabel(self.frame_about)
        self.label_update.setGeometry(QRect(40, 20, 600, 25))
        self.label_update.setObjectName("label_update")
        self.label_cur_version_tip = QLabel(self.frame_about)
        self.label_cur_version_tip.setGeometry(QRect(60, 60, 150, 16))
        self.label_cur_version_tip.setObjectName("label_cur_version_tip")
        self.label_open_source = QLabel(self.frame_about)
        self.label_open_source.setGeometry(QRect(40, 132, 600, 25))
        self.label_open_source.setObjectName("label_open_source")
        self.label_update_tip = QLabel(self.frame_about)
        self.label_update_tip.setGeometry(QRect(220, 90, 500, 16))
        self.label_update_tip.setObjectName("label_update_tip")
        self.pushButton_check_update = QPushButton(self.frame_about)
        self.pushButton_check_update.setGeometry(QRect(60, 85, 150, 25))
        self.pushButton_check_update.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_check_update.setObjectName("pushButton_check_update")
        self.label_open_source_tip = QLabel(self.frame_about)
        self.label_open_source_tip.setGeometry(QRect(60, 170, 500, 16))
        self.label_open_source_tip.setObjectName("label_open_source_tip")
        self.label_open_source_address_tip = QLabel(self.frame_about)
        self.label_open_source_address_tip.setGeometry(QRect(60, 200, 100, 20))
        self.label_open_source_address_tip.setObjectName("label_open_source_address_tip")
        self.label_open_source_address = QLabel(self.frame_about)
        self.label_open_source_address.setGeometry(QRect(160, 200, 500, 20))
        self.label_open_source_address.setObjectName("label_open_source_address")
        self.label_author_data = QLabel(self.frame_about)
        self.label_author_data.setGeometry(QRect(40, 244, 600, 25))
        self.label_author_data.setObjectName("label_author_data")
        self.label_author_name_tip = QLabel(self.frame_about)
        self.label_author_name_tip.setGeometry(QRect(60, 280, 70, 16))
        self.label_author_name_tip.setObjectName("label_author_name_tip")
        self.label_email_tip = QLabel(self.frame_about)
        self.label_email_tip.setGeometry(QRect(60, 310, 70, 16))
        self.label_email_tip.setObjectName("label_email_tip")
        self.label_author_name = QLabel(self.frame_about)
        self.label_author_name.setGeometry(QRect(140, 280, 100, 16))
        self.label_author_name.setObjectName("label_author_name")
        self.label_email = QLabel(self.frame_about)
        self.label_email.setGeometry(QRect(140, 310, 500, 16))
        self.label_email.setObjectName("label_email")
        self.label_cur_version = QLabel(self.frame_about)
        self.label_cur_version.setGeometry(QRect(210, 60, 100, 16))
        self.label_cur_version.setObjectName("label_cur_version")
        self.pushButton_close = QPushButton(self.widget_right)
        self.pushButton_close.setGeometry(QRect(730, 10, 20, 20))
        font = QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_minimize = QPushButton(self.widget_right)
        self.pushButton_minimize.setGeometry(QRect(690, 10, 20, 20))
        font = QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minimize.setFont(font)
        self.pushButton_minimize.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.widget_up = QWidget(Dialog)
        self.widget_up.setGeometry(QRect(260, 0, 690, 50))
        self.widget_up.setObjectName("widget_up")
        self.treeWidget.itemAt(0, 0).setSelected(True)
        self.frame_basics.raise_()
        # QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        '''
        Dialog.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinimizeButtonHint)
        Dialog.setAttribute(Qt.WA_TranslucentBackground)

        self.treeWidget.itemAt(0, 0).setSelected(True)
        self.frame_basics.raise_()
        '''
        from Languages import Strings
        Dialog.setWindowTitle(Strings.SETTING_DIALOG_TITLE)
        self.pushButton_minimize.setText('-')
        self.pushButton_close.setText('×')
        self.label_logo.setText(Strings.APP_NAME)
        self.treeWidget.headerItem().setText(0, '')
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, Strings.SETTING_BASICS)
        self.treeWidget.topLevelItem(1).setText(0, Strings.SETTING_SEARCH)
        self.treeWidget.topLevelItem(1).child(0).setText(0, Strings.SETTING_ENGINE_MANAGEMENT)
        self.treeWidget.topLevelItem(1).child(1).setText(0, Strings.SETTING_OTHER)
        self.treeWidget.topLevelItem(2).setText(0, Strings.SETTING_HOTKEY)
        self.treeWidget.topLevelItem(3).setText(0, Strings.SETTING_APPEARANCE)
        self.treeWidget.topLevelItem(4).setText(0, Strings.SETTING_ADVANCED)
        self.treeWidget.topLevelItem(5).setText(0, Strings.SETTING_ABOUT)
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_start_up.setText(Strings.SETTING_START_UP)
        self.label_show_tip.setText(Strings.SETTING_SHOW_TIP)
        self.checkBox_start_up.setText(Strings.SETTING_TURN_ON)
        self.checkBox_show_tip.setText(Strings.SETTING_TURN_ON)
        self.checkBox_private_mode.setText(Strings.SETTING_TURN_ON)
        self.label_private_mode.setText(Strings.SETTING_PRIVATE_MODE)
        self.label_private_mode_tip1.setText(Strings.SETTING_PRIVATE_MODE_TIP1)
        self.label_private_mode_tip2.setText(Strings.SETTING_PRIVATE_MODE_TIP2)
        self.label_browser_path.setText(Strings.SETTING_BROWSER_PATH)
        self.pushButton_browser_path.setText('...')
        self.label_suggestion_engine.setText(Strings.SETTING_SUGGEST_ENGINE)
        self.comboBox_suggestion_engine.setItemText(0, Strings.SETTING_360)
        self.comboBox_suggestion_engine.setItemText(1, Strings.SETTING_DOGE)
        self.comboBox_suggestion_engine.setItemText(2, Strings.SETTING_GOOGLE)
        self.label_search_suggestion.setText(Strings.SETTING_SUGGEST)
        self.checkBox_search_suggestion.setText(Strings.SETTING_TURN_ON)
        self.label_language.setText(Strings.SETTING_LANGUAGE)
        self.label_fillet.setText(Strings.SETTING_FILLET)
        self.label_opacity.setText(Strings.SETTING_OPACITY)
        self.comboBox_opacity.setItemText(0, '0.9')
        self.comboBox_opacity.setItemText(1, '0.8')
        self.comboBox_opacity.setItemText(2, '0.7')
        self.comboBox_opacity.setItemText(3, '0.6')
        self.comboBox_opacity.setItemText(4, '0.5')
        self.comboBox_opacity.setItemText(5, '1')
        self.comboBox_fillet.setItemText(0, '0')
        self.comboBox_fillet.setItemText(1, '1')
        self.comboBox_fillet.setItemText(2, '2')
        self.comboBox_fillet.setItemText(3, '3')
        self.comboBox_fillet.setItemText(4, '4')
        self.comboBox_fillet.setItemText(5, '5')
        self.comboBox_fillet.setItemText(6, '6')
        self.comboBox_fillet.setItemText(7, '7')
        self.comboBox_fillet.setItemText(8, '8')
        self.comboBox_fillet.setItemText(9, '9')
        self.comboBox_fillet.setItemText(10, '10')
        self.label_distance.setText(Strings.SETTING_DISTANCE)
        self.comboBox_distance.setItemText(0, '0')
        self.comboBox_distance.setItemText(1, '1')
        self.comboBox_distance.setItemText(2, '2')
        self.comboBox_distance.setItemText(3, '3')
        self.comboBox_distance.setItemText(4, '4')
        self.comboBox_distance.setItemText(5, '5')
        self.comboBox_distance.setItemText(6, '6')
        self.comboBox_distance.setItemText(7, '7')
        self.comboBox_distance.setItemText(8, '8')
        self.comboBox_distance.setItemText(9, '9')
        self.comboBox_distance.setItemText(10, '10')
        self.label_theme.setText(Strings.SETTING_THEME)
        self.groupBox_blue.setTitle(Strings.SETTING_COLOR_BLUE)
        self.groupBox_green.setTitle(Strings.SETTING_COLOR_GREEN)
        self.groupBox_yellow.setTitle(Strings.SETTING_COLOR_YELLOW)
        self.groupBox_orange.setTitle(Strings.SETTING_COLOR_ORANGE)
        self.groupBox_red.setTitle(Strings.SETTING_COLOR_RED)
        self.groupBox_purple.setTitle(Strings.SETTING_COLOR_PURPLE)
        self.groupBox_grey.setTitle(Strings.SETTING_COLOR_GREY)
        self.groupBox_black.setTitle(Strings.SETTING_COLOR_BLACK)
        self.groupBox_custom.setTitle(Strings.SETTING_COLOR_CUSTOM)
        self.label_no_sleep.setText(Strings.SETTING_NO_SLEEP)
        self.checkBox_no_sleep.setText(Strings.SETTING_TURN_ON)
        self.label_key_type.setText(Strings.SETTING_HOTKEY_TYPE)
        self.radioButton_single_key.setText(Strings.SETTING_SINGLE_KEY)
        self.radioButton_multiple_key.setText(Strings.SETTING_MULTIPLE_KEY)
        self.comboBox_interval.setItemText(0, '0.5')
        self.comboBox_interval.setItemText(1, '0.1')
        self.comboBox_interval.setItemText(2, '0.2')
        self.comboBox_interval.setItemText(3, '0.3')
        self.comboBox_interval.setItemText(4, '0.4')
        self.comboBox_interval.setItemText(5, '0.6')
        self.comboBox_interval.setItemText(6, '0.7')
        self.comboBox_interval.setItemText(7, '0.8')
        self.comboBox_interval.setItemText(8, '0.9')
        self.comboBox_interval.setItemText(9, '1')
        self.comboBox_repetitions.setItemText(0, '2')
        self.comboBox_repetitions.setItemText(1, '3')
        self.comboBox_repetitions.setItemText(2, '4')
        self.comboBox_repetitions.setItemText(3, '5')
        self.comboBox_repetitions.setItemText(4, '1')
        self.label_key_setting_tip.setText(Strings.SETTING_KEY_SETTING_TIP)
        self.label_interval.setText(Strings.SETTING_INTERVAL)
        self.label_repetitions.setText(Strings.SETTING_REPETITIONS)
        self.label_key_setting.setText(Strings.SETTING_KEY_SETTING)
        self.label_suggestion_clear_cache.setText(Strings.SETTING_SUGGESTION_CLEAR_CACHE)
        self.label_suggestion_cache_count1.setText(Strings.SETTING_SUGGESTION_COUNT)
        self.pushButton_suggestion_clear_cache.setText(Strings.SETTING_CLEAR)
        self.label_backup.setText(Strings.SETTING_BACKUP_AND_RECOVERY)
        self.pushButton_import_settings.setText(Strings.SETTING_IMPORT_SETTING)
        self.pushButton_export_settings.setText(Strings.SETTING_EXPORT_SETTING)
        self.model.setHorizontalHeaderLabels([Strings.SETTING_KEYWORD, Strings.SETTING_ICON, Strings.SETTING_URL])
        self.tableView_search_engine.setItemDelegateForColumn(1,
                                                              IconDelegate(Strings.SETTING_SELECT_ICON,
                                                                           filter='*.ico;*.jpg;*.png',
                                                                           parent=self.tableView_search_engine))
        self.table_menu.actions.get('set_default_engine').setText(Strings.SETTING_SET_DEFAULT_ENGINE)
        self.table_menu.actions.get('delete').setText(Strings.SETTING_DELETE)
        self.label_update.setText(Strings.SETTING_UPDATE)
        self.label_cur_version_tip.setText(Strings.SETTING_CUR_VERSION_TIP)
        self.label_cur_version.setText(Strings.SETTING_CUR_VERSION)
        self.pushButton_check_update.setText(Strings.SETTING_CHECK_UPDATE)
        self.label_update_tip.setOpenExternalLinks(True)
        self.label_open_source.setText(Strings.SETTING_OPEN_SOURCE)
        self.label_open_source_tip.setText(Strings.SETTING_OPEN_SOURCE_TIP)
        self.label_open_source_address.setOpenExternalLinks(True)
        self.label_open_source_address.setText('<style>a{color:black;}</style><a href="{}">{}</a>'.replace('{}', Strings.SETTING_OPEN_SOURCE_ADDRESS))
        self.label_open_source_address_tip.setText(Strings.SETTING_OPEN_SOURCE_ADDRESS_TIP)
        self.label_author_data.setText(Strings.SETTING_AUTHOR_DATA)
        self.label_author_name.setText(Strings.AUTHOR_NAME)
        self.label_author_name_tip.setText(Strings.SETTING_AUTHOR_NAME_TIP)
        self.label_email.setText(Strings.SETTING_EMAIL)
        self.label_email_tip.setText(Strings.SETTING_EMAIL_TIP)

