# -*- coding: utf-8 -*-
#
# Copyright 2020 Xpp521
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Form implementation generated from reading ui file 'SettingDialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
from os.path import join
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon, QFont, QCursor


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1025, 675)
        Dialog.setModal(False)
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget_left = QtWidgets.QWidget(Dialog)
        self.widget_left.setGeometry(QtCore.QRect(0, 0, 260, 675))
        font = QFont()
        font.setPointSize(9)
        self.widget_left.setFont(font)
        self.widget_left.setObjectName("widget_left")
        self.treeWidget = QtWidgets.QTreeWidget(self.widget_left)
        self.treeWidget.setGeometry(QtCore.QRect(0, 140, 260, 400))
        font = QFont()
        font.setFamily("Arial")
        self.treeWidget.setFont(font)
        self.treeWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeWidget.setIndentation(24)
        self.treeWidget.setRootIsDecorated(True)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.label_logo = QtWidgets.QLabel(self.widget_left)
        self.label_logo.setGeometry(QtCore.QRect(30, 20, 200, 100))
        font = QFont()
        font.setFamily("MV Boli")
        font.setPointSize(30)
        self.label_logo.setFont(font)
        self.label_logo.setObjectName("label_logo")
        self.widget_right = QtWidgets.QWidget(Dialog)
        self.widget_right.setGeometry(QtCore.QRect(260, 0, 765, 675))
        self.widget_right.setObjectName("widget_right")
        self.frame_advanced = QtWidgets.QFrame(self.widget_right)
        self.frame_advanced.setGeometry(QtCore.QRect(0, 50, 765, 600))
        self.frame_advanced.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_advanced.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_advanced.setObjectName("frame_advanced")
        self.label_no_sleep = QtWidgets.QLabel(self.frame_advanced)
        self.label_no_sleep.setGeometry(QtCore.QRect(40, 20, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_no_sleep.setFont(font)
        self.label_no_sleep.setObjectName("label_no_sleep")
        self.checkBox_no_sleep = QtWidgets.QCheckBox(self.frame_advanced)
        self.checkBox_no_sleep.setGeometry(QtCore.QRect(60, 50, 100, 20))
        self.checkBox_no_sleep.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_no_sleep.setObjectName("checkBox_no_sleep")
        self.label_backup = QtWidgets.QLabel(self.frame_advanced)
        self.label_backup.setGeometry(QtCore.QRect(40, 132, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_backup.setFont(font)
        self.label_backup.setObjectName("label_backup")
        self.pushButton_import_settings = QtWidgets.QPushButton(self.frame_advanced)
        self.pushButton_import_settings.setGeometry(QtCore.QRect(190, 162, 100, 25))
        self.pushButton_import_settings.setObjectName("pushButton_import_settings")
        self.pushButton_export_settings = QtWidgets.QPushButton(self.frame_advanced)
        self.pushButton_export_settings.setGeometry(QtCore.QRect(60, 162, 100, 25))
        self.pushButton_export_settings.setObjectName("pushButton_export_settings")
        self.frame_search_other = QtWidgets.QFrame(self.widget_right)
        self.frame_search_other.setGeometry(QtCore.QRect(0, 50, 765, 600))
        self.frame_search_other.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search_other.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search_other.setObjectName("frame_search_other")
        self.checkBox_private_mode = QtWidgets.QCheckBox(self.frame_search_other)
        self.checkBox_private_mode.setGeometry(QtCore.QRect(60, 538, 91, 20))
        self.checkBox_private_mode.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_private_mode.setObjectName("checkBox_private_mode")
        self.label_private_mode = QtWidgets.QLabel(self.frame_search_other)
        self.label_private_mode.setGeometry(QtCore.QRect(40, 468, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_private_mode.setFont(font)
        self.label_private_mode.setObjectName("label_private_mode")
        self.label_private_mode_tip1 = QtWidgets.QLabel(self.frame_search_other)
        self.label_private_mode_tip1.setGeometry(QtCore.QRect(60, 498, 690, 16))
        self.label_private_mode_tip1.setObjectName("label_private_mode_tip1")
        self.label_browser_path = QtWidgets.QLabel(self.frame_search_other)
        self.label_browser_path.setGeometry(QtCore.QRect(40, 356, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_browser_path.setFont(font)
        self.label_browser_path.setObjectName("label_browser_path")
        self.pushButton_browser_path = QtWidgets.QPushButton(self.frame_search_other)
        self.pushButton_browser_path.setGeometry(QtCore.QRect(570, 386, 35, 25))
        self.pushButton_browser_path.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_browser_path.setFlat(False)
        self.pushButton_browser_path.setObjectName("pushButton_browser_path")
        self.lineEdit_browser_path = QtWidgets.QLineEdit(self.frame_search_other)
        self.lineEdit_browser_path.setGeometry(QtCore.QRect(60, 386, 500, 25))
        self.lineEdit_browser_path.setReadOnly(True)
        self.lineEdit_browser_path.setObjectName("lineEdit_browser_path")
        self.label_suggestion_engine = QtWidgets.QLabel(self.frame_search_other)
        self.label_suggestion_engine.setGeometry(QtCore.QRect(40, 132, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_suggestion_engine.setFont(font)
        self.label_suggestion_engine.setObjectName("label_suggestion_engine")
        self.comboBox_suggest_engine = QtWidgets.QComboBox(self.frame_search_other)
        self.comboBox_suggest_engine.setGeometry(QtCore.QRect(60, 162, 150, 22))
        self.comboBox_suggest_engine.setObjectName("comboBox_suggest_engine")
        self.comboBox_suggest_engine.addItem("")
        self.comboBox_suggest_engine.addItem("")
        self.comboBox_suggest_engine.addItem("")
        self.label_search_suggestion = QtWidgets.QLabel(self.frame_search_other)
        self.label_search_suggestion.setGeometry(QtCore.QRect(40, 20, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_search_suggestion.setFont(font)
        self.label_search_suggestion.setObjectName("label_search_suggestion")
        self.checkBox_search_suggestion = QtWidgets.QCheckBox(self.frame_search_other)
        self.checkBox_search_suggestion.setGeometry(QtCore.QRect(60, 50, 100, 20))
        self.checkBox_search_suggestion.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_search_suggestion.setObjectName("checkBox_search_suggestion")
        self.label_private_mode_tip2 = QtWidgets.QLabel(self.frame_search_other)
        self.label_private_mode_tip2.setGeometry(QtCore.QRect(60, 518, 690, 16))
        self.label_private_mode_tip2.setObjectName("label_private_mode_tip2")
        self.label_suggestion_clear_cache = QtWidgets.QLabel(self.frame_search_other)
        self.label_suggestion_clear_cache.setGeometry(QtCore.QRect(40, 244, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_suggestion_clear_cache.setFont(font)
        self.label_suggestion_clear_cache.setObjectName("label_suggestion_clear_cache")
        self.pushButton_suggestion_clear_cache = QtWidgets.QPushButton(self.frame_search_other)
        self.pushButton_suggestion_clear_cache.setGeometry(QtCore.QRect(60, 294, 100, 25))
        self.pushButton_suggestion_clear_cache.setObjectName("pushButton_suggestion_clear_cache")
        self.label_suggestion_cache_count1 = QtWidgets.QLabel(self.frame_search_other)
        self.label_suggestion_cache_count1.setGeometry(QtCore.QRect(60, 274, 100, 16))
        self.label_suggestion_cache_count1.setObjectName("label_suggestion_cache_count1")
        self.label_suggestion_cache_count2 = QtWidgets.QLabel(self.frame_search_other)
        self.label_suggestion_cache_count2.setGeometry(QtCore.QRect(160, 274, 100, 16))
        self.label_suggestion_cache_count2.setObjectName("label_suggestion_cache_count2")
        self.frame_hotkey = QtWidgets.QFrame(self.widget_right)
        self.frame_hotkey.setGeometry(QtCore.QRect(0, 50, 765, 600))
        self.frame_hotkey.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hotkey.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hotkey.setObjectName("frame_hotkey")
        self.label_key_type = QtWidgets.QLabel(self.frame_hotkey)
        self.label_key_type.setGeometry(QtCore.QRect(40, 20, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_key_type.setFont(font)
        self.label_key_type.setObjectName("label_key_type")
        self.radioButton_single_key = QtWidgets.QRadioButton(self.frame_hotkey)
        self.radioButton_single_key.setGeometry(QtCore.QRect(60, 50, 200, 20))
        self.radioButton_single_key.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_single_key.setObjectName("radioButton_single_key")
        self.radioButton_multiple_key = QtWidgets.QRadioButton(self.frame_hotkey)
        self.radioButton_multiple_key.setGeometry(QtCore.QRect(60, 80, 200, 20))
        self.radioButton_multiple_key.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_multiple_key.setObjectName("radioButton_multiple_key")
        self.lineEdit_key_setting = QtWidgets.QLineEdit(self.frame_hotkey)
        self.lineEdit_key_setting.setGeometry(QtCore.QRect(60, 182, 150, 22))
        self.lineEdit_key_setting.setReadOnly(True)
        self.lineEdit_key_setting.setObjectName("lineEdit_key_setting")
        self.label_key_setting_tip = QtWidgets.QLabel(self.frame_hotkey)
        self.label_key_setting_tip.setGeometry(QtCore.QRect(60, 162, 500, 16))
        self.label_key_setting_tip.setObjectName("label_key_setting_tip")
        self.label_key_setting = QtWidgets.QLabel(self.frame_hotkey)
        self.label_key_setting.setGeometry(QtCore.QRect(40, 132, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_key_setting.setFont(font)
        self.label_key_setting.setObjectName("label_key_setting")
        self.comboBox_interval = QtWidgets.QComboBox(self.frame_hotkey)
        self.comboBox_interval.setGeometry(QtCore.QRect(60, 386, 150, 22))
        self.comboBox_interval.setObjectName("comboBox_interval")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.comboBox_interval.addItem("")
        self.label_interval = QtWidgets.QLabel(self.frame_hotkey)
        self.label_interval.setGeometry(QtCore.QRect(40, 356, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_interval.setFont(font)
        self.label_interval.setObjectName("label_interval")
        self.comboBox_repetitions = QtWidgets.QComboBox(self.frame_hotkey)
        self.comboBox_repetitions.setGeometry(QtCore.QRect(60, 274, 150, 22))
        self.comboBox_repetitions.setObjectName("comboBox_repetitions")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.comboBox_repetitions.addItem("")
        self.label_repetitions = QtWidgets.QLabel(self.frame_hotkey)
        self.label_repetitions.setGeometry(QtCore.QRect(40, 244, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_repetitions.setFont(font)
        self.label_repetitions.setObjectName("label_repetitions")
        self.frame_engine_management = QtWidgets.QFrame(self.widget_right)
        self.frame_engine_management.setGeometry(QtCore.QRect(0, 50, 765, 600))
        self.frame_engine_management.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_engine_management.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_engine_management.setObjectName("frame_engine_management")
        self.tableWidget_search_engine = QtWidgets.QTableWidget(self.frame_engine_management)
        self.tableWidget_search_engine.setGeometry(QtCore.QRect(40, 20, 685, 192))
        self.tableWidget_search_engine.setObjectName("tableWidget_search_engine")
        self.tableWidget_search_engine.setColumnCount(3)
        self.tableWidget_search_engine.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_engine.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_engine.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_engine.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_engine.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_engine.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_engine.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_search_engine.setItem(0, 2, item)
        self.frame_basics = QtWidgets.QFrame(self.widget_right)
        self.frame_basics.setGeometry(QtCore.QRect(0, 50, 765, 600))
        self.frame_basics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_basics.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_basics.setObjectName("frame_basics")
        self.label_start_up = QtWidgets.QLabel(self.frame_basics)
        self.label_start_up.setGeometry(QtCore.QRect(40, 20, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_start_up.setFont(font)
        self.label_start_up.setObjectName("label_start_up")
        self.label_show_tip = QtWidgets.QLabel(self.frame_basics)
        self.label_show_tip.setGeometry(QtCore.QRect(40, 132, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_show_tip.setFont(font)
        self.label_show_tip.setObjectName("label_show_tip")
        self.checkBox_start_up = QtWidgets.QCheckBox(self.frame_basics)
        self.checkBox_start_up.setGeometry(QtCore.QRect(60, 50, 100, 20))
        self.checkBox_start_up.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_start_up.setObjectName("checkBox_start_up")
        self.checkBox_show_tip = QtWidgets.QCheckBox(self.frame_basics)
        self.checkBox_show_tip.setGeometry(QtCore.QRect(60, 162, 100, 20))
        self.checkBox_show_tip.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_show_tip.setObjectName("checkBox_show_tip")
        self.comboBox_language = QtWidgets.QComboBox(self.frame_basics)
        self.comboBox_language.setGeometry(QtCore.QRect(60, 274, 150, 22))
        self.comboBox_language.setObjectName("comboBox_language")
        self.comboBox_language.addItem("")
        self.comboBox_language.addItem("")
        self.label_language = QtWidgets.QLabel(self.frame_basics)
        self.label_language.setGeometry(QtCore.QRect(41, 244, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_language.setFont(font)
        self.label_language.setObjectName("label_language")
        self.frame_appearance = QtWidgets.QFrame(self.widget_right)
        self.frame_appearance.setGeometry(QtCore.QRect(0, 50, 765, 600))
        self.frame_appearance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_appearance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_appearance.setObjectName("frame_appearance")
        self.label_opacity = QtWidgets.QLabel(self.frame_appearance)
        self.label_opacity.setGeometry(QtCore.QRect(40, 20, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_opacity.setFont(font)
        self.label_opacity.setObjectName("label_opacity")
        self.comboBox_opacity = QtWidgets.QComboBox(self.frame_appearance)
        self.comboBox_opacity.setGeometry(QtCore.QRect(60, 50, 150, 22))
        self.comboBox_opacity.setObjectName("comboBox_opacity")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.comboBox_opacity.addItem("")
        self.label_fillet = QtWidgets.QLabel(self.frame_appearance)
        self.label_fillet.setGeometry(QtCore.QRect(40, 132, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_fillet.setFont(font)
        self.label_fillet.setObjectName("label_fillet")
        self.comboBox_fillet = QtWidgets.QComboBox(self.frame_appearance)
        self.comboBox_fillet.setGeometry(QtCore.QRect(60, 162, 150, 22))
        self.comboBox_fillet.setObjectName("comboBox_fillet")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.comboBox_fillet.addItem("")
        self.label_theme = QtWidgets.QLabel(self.frame_appearance)
        self.label_theme.setGeometry(QtCore.QRect(40, 356, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_theme.setFont(font)
        self.label_theme.setObjectName("label_theme")
        self.label_distance = QtWidgets.QLabel(self.frame_appearance)
        self.label_distance.setGeometry(QtCore.QRect(40, 244, 600, 25))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_distance.setFont(font)
        self.label_distance.setObjectName("label_distance")
        self.comboBox_distance = QtWidgets.QComboBox(self.frame_appearance)
        self.comboBox_distance.setGeometry(QtCore.QRect(60, 274, 150, 22))
        self.comboBox_distance.setObjectName("comboBox_distance")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.groupBox_blue = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_blue.setGeometry(QtCore.QRect(40, 396, 70, 80))
        self.groupBox_blue.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_blue.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_blue.setFlat(False)
        self.groupBox_blue.setObjectName("groupBox_blue")
        self.pushButton_blue = QtWidgets.QPushButton(self.groupBox_blue)
        self.pushButton_blue.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_blue.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_blue.setText("")
        self.pushButton_blue.setObjectName("pushButton_blue")
        self.groupBox_green = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_green.setGeometry(QtCore.QRect(130, 396, 70, 80))
        self.groupBox_green.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_green.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_green.setFlat(False)
        self.groupBox_green.setObjectName("groupBox_green")
        self.pushButton_green = QtWidgets.QPushButton(self.groupBox_green)
        self.pushButton_green.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_green.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_green.setText("")
        self.pushButton_green.setObjectName("pushButton_green")
        self.groupBox_yellow = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_yellow.setGeometry(QtCore.QRect(220, 396, 70, 80))
        self.groupBox_yellow.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_yellow.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_yellow.setFlat(False)
        self.groupBox_yellow.setObjectName("groupBox_yellow")
        self.pushButton_yellow = QtWidgets.QPushButton(self.groupBox_yellow)
        self.pushButton_yellow.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_yellow.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_yellow.setText("")
        self.pushButton_yellow.setObjectName("pushButton_yellow")
        self.groupBox_orange = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_orange.setGeometry(QtCore.QRect(310, 396, 70, 80))
        self.groupBox_orange.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_orange.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_orange.setFlat(False)
        self.groupBox_orange.setObjectName("groupBox_orange")
        self.pushButton_orange = QtWidgets.QPushButton(self.groupBox_orange)
        self.pushButton_orange.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_orange.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_orange.setText("")
        self.pushButton_orange.setObjectName("pushButton_orange")
        self.groupBox_red = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_red.setGeometry(QtCore.QRect(400, 396, 70, 80))
        self.groupBox_red.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_red.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_red.setFlat(False)
        self.groupBox_red.setObjectName("groupBox_red")
        self.pushButton_red = QtWidgets.QPushButton(self.groupBox_red)
        self.pushButton_red.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_red.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_red.setText("")
        self.pushButton_red.setObjectName("pushButton_red")
        self.groupBox_purple = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_purple.setGeometry(QtCore.QRect(490, 396, 70, 80))
        self.groupBox_purple.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_purple.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_purple.setFlat(False)
        self.groupBox_purple.setObjectName("groupBox_purple")
        self.pushButton_purple = QtWidgets.QPushButton(self.groupBox_purple)
        self.pushButton_purple.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_purple.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_purple.setText("")
        self.pushButton_purple.setObjectName("pushButton_purple")
        self.groupBox_grey = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_grey.setGeometry(QtCore.QRect(580, 396, 70, 80))
        self.groupBox_grey.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_grey.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_grey.setFlat(False)
        self.groupBox_grey.setObjectName("groupBox_grey")
        self.pushButton_grey = QtWidgets.QPushButton(self.groupBox_grey)
        self.pushButton_grey.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_grey.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_grey.setText("")
        self.pushButton_grey.setObjectName("pushButton_grey")
        self.groupBox_black = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_black.setGeometry(QtCore.QRect(670, 396, 70, 80))
        self.groupBox_black.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_black.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_black.setFlat(False)
        self.groupBox_black.setObjectName("groupBox_black")
        self.pushButton_black = QtWidgets.QPushButton(self.groupBox_black)
        self.pushButton_black.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_black.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_black.setText("")
        self.pushButton_black.setObjectName("pushButton_black")
        self.groupBox_custom = QtWidgets.QGroupBox(self.frame_appearance)
        self.groupBox_custom.setGeometry(QtCore.QRect(40, 486, 70, 80))
        self.groupBox_custom.setCursor(QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_custom.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_custom.setFlat(False)
        self.groupBox_custom.setCheckable(False)
        self.groupBox_custom.setObjectName("groupBox_custom")
        self.pushButton_custom = QtWidgets.QPushButton(self.groupBox_custom)
        self.pushButton_custom.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.pushButton_custom.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_custom.setText("")
        self.pushButton_custom.setObjectName("pushButton_custom")
        self.pushButton_close = QtWidgets.QPushButton(self.widget_right)
        self.pushButton_close.setGeometry(QtCore.QRect(730, 10, 20, 20))
        font = QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_minimize = QtWidgets.QPushButton(self.widget_right)
        self.pushButton_minimize.setGeometry(QtCore.QRect(690, 10, 20, 20))
        font = QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minimize.setFont(font)
        self.pushButton_minimize.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.widget_up = QtWidgets.QWidget(Dialog)
        self.widget_up.setGeometry(QtCore.QRect(260, 0, 690, 50))
        self.widget_up.setObjectName("widget_up")
        self.treeWidget.itemAt(0, 0).setSelected(True)
        self.frame_basics.raise_()
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        '''
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.treeWidget.itemAt(0, 0).setSelected(True)
        self.frame_basics.raise_()
        '''
        Dialog.setWindowIcon(QIcon(join('Icons', 'XSearch.ico')))
        from Strings import Strings
        Dialog.setWindowTitle(Strings.SETTING_DIALOG_TITLE)
        self.pushButton_minimize.setText('-')
        self.pushButton_close.setText('×')
        self.label_logo.setText(Strings.APP_NAME)
        self.treeWidget.headerItem().setText(0, '')
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, Strings.SETTING_BASICS)
        self.treeWidget.topLevelItem(1).setText(0, Strings.SETTING_SEARCH)
        self.treeWidget.topLevelItem(1).child(0).setText(0, Strings.SETTING_ENGINE_MANAGEMENT)
        self.treeWidget.topLevelItem(1).child(1).setText(0, Strings.SETTING_OTHER)
        self.treeWidget.topLevelItem(2).setText(0, Strings.SETTING_HOTKEY)
        self.treeWidget.topLevelItem(3).setText(0, Strings.SETTING_APPEARANCE)
        self.treeWidget.topLevelItem(4).setText(0, Strings.SETTING_ADVANCED)
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_start_up.setText(Strings.SETTING_START_UP)
        self.label_show_tip.setText(Strings.SETTING_SHOW_TIP)
        self.checkBox_start_up.setText(Strings.SETTING_TURN_ON)
        self.checkBox_show_tip.setText(Strings.SETTING_TURN_ON)
        self.checkBox_private_mode.setText(Strings.SETTING_TURN_ON)
        self.label_private_mode.setText(Strings.SETTING_PRIVATE_MODE)
        self.label_private_mode_tip1.setText(Strings.SETTING_PRIVATE_MODE_TIP1)
        self.label_private_mode_tip2.setText(Strings.SETTING_PRIVATE_MODE_TIP2)
        self.label_browser_path.setText(Strings.SETTING_BROWSER_PATH)
        self.pushButton_browser_path.setText('...')
        self.label_suggestion_engine.setText(Strings.SETTING_SUGGEST_ENGINE)
        self.comboBox_suggest_engine.setItemText(0, Strings.SETTING_360)
        self.comboBox_suggest_engine.setItemText(1, Strings.SETTING_BAIDU)
        self.comboBox_suggest_engine.setItemText(2, Strings.SETTING_SOGOU)
        self.label_search_suggestion.setText(Strings.SETTING_SUGGEST)
        self.checkBox_search_suggestion.setText(Strings.SETTING_TURN_ON)
        self.label_language.setText(Strings.SETTING_LANGUAGE)
        self.comboBox_language.setItemText(0, Strings.SETTING_SIMPLIFIED_CHINESE)
        self.comboBox_language.setItemText(1, Strings.SETTING_ENGLISH)
        self.label_fillet.setText(Strings.SETTING_FILLET)
        self.label_opacity.setText(Strings.SETTING_OPACITY)
        self.comboBox_opacity.setItemText(0, '0.9')
        self.comboBox_opacity.setItemText(1, '0.8')
        self.comboBox_opacity.setItemText(2, '0.7')
        self.comboBox_opacity.setItemText(3, '0.6')
        self.comboBox_opacity.setItemText(4, '0.5')
        self.comboBox_opacity.setItemText(5, '1')
        self.comboBox_fillet.setItemText(0, '0')
        self.comboBox_fillet.setItemText(1, '1')
        self.comboBox_fillet.setItemText(2, '2')
        self.comboBox_fillet.setItemText(3, '3')
        self.comboBox_fillet.setItemText(4, '4')
        self.comboBox_fillet.setItemText(5, '5')
        self.comboBox_fillet.setItemText(6, '6')
        self.comboBox_fillet.setItemText(7, '7')
        self.comboBox_fillet.setItemText(8, '8')
        self.comboBox_fillet.setItemText(9, '9')
        self.comboBox_fillet.setItemText(10, '10')
        self.label_distance.setText(Strings.SETTING_DISTANCE)
        self.comboBox_distance.setItemText(0, '0')
        self.comboBox_distance.setItemText(1, '1')
        self.comboBox_distance.setItemText(2, '2')
        self.comboBox_distance.setItemText(3, '3')
        self.comboBox_distance.setItemText(4, '4')
        self.comboBox_distance.setItemText(5, '5')
        self.comboBox_distance.setItemText(6, '6')
        self.comboBox_distance.setItemText(7, '7')
        self.comboBox_distance.setItemText(8, '8')
        self.comboBox_distance.setItemText(9, '9')
        self.comboBox_distance.setItemText(10, '10')
        self.label_theme.setText(Strings.SETTING_THEME)
        self.groupBox_blue.setTitle(Strings.SETTING_COLOR_BLUE)
        self.groupBox_green.setTitle(Strings.SETTING_COLOR_GREEN)
        self.groupBox_yellow.setTitle(Strings.SETTING_COLOR_YELLOW)
        self.groupBox_orange.setTitle(Strings.SETTING_COLOR_ORANGE)
        self.groupBox_red.setTitle(Strings.SETTING_COLOR_RED)
        self.groupBox_purple.setTitle(Strings.SETTING_COLOR_PURPLE)
        self.groupBox_grey.setTitle(Strings.SETTING_COLOR_GREY)
        self.groupBox_black.setTitle(Strings.SETTING_COLOR_BLACK)
        self.groupBox_custom.setTitle(Strings.SETTING_COLOR_CUSTOM)
        self.label_no_sleep.setText(Strings.SETTING_NO_SLEEP)
        self.checkBox_no_sleep.setText(Strings.SETTING_TURN_ON)
        self.label_key_type.setText(Strings.SETTING_HOTKEY_TYPE)
        self.radioButton_single_key.setText(Strings.SETTING_SINGLE_KEY)
        self.radioButton_multiple_key.setText(Strings.SETTING_MULTIPLE_KEY)
        self.comboBox_interval.setItemText(0, '0.5')
        self.comboBox_interval.setItemText(1, '0.1')
        self.comboBox_interval.setItemText(2, '0.2')
        self.comboBox_interval.setItemText(3, '0.3')
        self.comboBox_interval.setItemText(4, '0.4')
        self.comboBox_interval.setItemText(5, '0.6')
        self.comboBox_interval.setItemText(6, '0.7')
        self.comboBox_interval.setItemText(7, '0.8')
        self.comboBox_interval.setItemText(8, '0.9')
        self.comboBox_interval.setItemText(9, '1')
        self.comboBox_repetitions.setItemText(0, '2')
        self.comboBox_repetitions.setItemText(1, '3')
        self.comboBox_repetitions.setItemText(2, '4')
        self.comboBox_repetitions.setItemText(3, '5')
        self.comboBox_repetitions.setItemText(4, '1')
        self.label_key_setting_tip.setText(Strings.SETTING_KEY_SETTING_TIP)
        self.label_interval.setText(Strings.SETTING_INTERVAL)
        self.label_repetitions.setText(Strings.SETTING_REPETITIONS)
        self.label_key_setting.setText(Strings.SETTING_KEY_SETTING)
        self.comboBox_suggest_engine.setItemData(0, '360')
        self.comboBox_suggest_engine.setItemData(1, 'baidu')
        self.comboBox_suggest_engine.setItemData(2, 'sogou')
        self.comboBox_language.setItemData(0, 'cn')
        self.comboBox_language.setItemData(1, 'en')
        # item = self.tableWidget_search_engine.verticalHeaderItem(0)
        # item.setText("行")
        item = self.tableWidget_search_engine.horizontalHeaderItem(0)
        item.setText("关键词")
        item = self.tableWidget_search_engine.horizontalHeaderItem(1)
        item.setText("图标")
        item = self.tableWidget_search_engine.horizontalHeaderItem(2)
        item.setText("网址")
        __sortingEnabled = self.tableWidget_search_engine.isSortingEnabled()
        self.tableWidget_search_engine.setSortingEnabled(False)
        item = self.tableWidget_search_engine.item(0, 0)
        item.setText('baidu')
        item = self.tableWidget_search_engine.item(0, 1)
        item.setText('baidu.png')
        item = self.tableWidget_search_engine.item(0, 2)
        item.setText('https://www.baidu.com/s?wd=%s')
        self.tableWidget_search_engine.setSortingEnabled(__sortingEnabled)
        self.label_suggestion_clear_cache.setText(Strings.SETTING_SUGGESTION_CLEAR_CACHE)
        self.label_suggestion_cache_count1.setText(Strings.SETTING_SUGGESTION_COUNT)
        self.pushButton_suggestion_clear_cache.setText(Strings.SETTING_CLEAR)
        self.label_backup.setText(Strings.SETTING_BACKUP_AND_RECOVERY)
        self.pushButton_import_settings.setText(Strings.SETTING_IMPORT_SETTING)
        self.pushButton_export_settings.setText(Strings.SETTING_EXPORT_SETTING)
